export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-900 text-white p-8 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-gray-400 mb-4">Last updated: January 17, 2026</p>
      
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
        <p className="text-gray-300">
          By using MailSync Bot, you agree to these Terms of Service. If you do not agree, 
          please do not use the service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
        <p className="text-gray-300">
          MailSync Bot is a Telegram bot that connects to your Gmail account to provide 
          AI-powered email summaries, notifications, and reply capabilities.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">3. User Responsibilities</h2>
        <p className="text-gray-300">You agree to:</p>
        <ul className="list-disc list-inside text-gray-300 space-y-1">
          <li>Provide accurate information</li>
          <li>Keep your account credentials secure</li>
          <li>Use the service in compliance with all applicable laws</li>
          <li>Not use the service for spam or malicious purposes</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">4. Gmail Access</h2>
        <p className="text-gray-300">
          By connecting your Gmail account, you authorize MailSync Bot to read your emails, 
          send emails on your behalf (when you use the reply feature), and modify email labels.
          You can revoke this access at any time.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">5. AI-Generated Content</h2>
        <p className="text-gray-300">
          Email summaries and suggested replies are generated by AI and may not always be accurate.
          You are responsible for reviewing any content before sending replies.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">6. Limitation of Liability</h2>
        <p className="text-gray-300">
          MailSync Bot is provided "as is" without warranties. We are not liable for any 
          damages arising from your use of the service, including but not limited to 
          missed emails, incorrect summaries, or unauthorized access.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">7. Termination</h2>
        <p className="text-gray-300">
          We reserve the right to terminate or suspend your access to the service at any time,
          for any reason, without prior notice.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">8. Changes to Terms</h2>
        <p className="text-gray-300">
          We may update these terms at any time. Continued use of the service after changes 
          constitutes acceptance of the new terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">9. Contact</h2>
        <p className="text-gray-300">
          For questions about these terms, contact us at: info@ezy4me.com
        </p>
      </section>
    </div>
  );
}
